### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#11]
-  Additionally, I need to open another issue about things to add to the course. In the projects students encountered a lot of missing data, and we didn’t formally discuss what to do with such tings in this book… So we should at least discuss some aspect of this here (not fully cover imputation for example, but instead discuss options such as removing observations, and doing simple mean imputation perhaps, and when to do which).

**Comment by trevorcampbell** [comment]
I agree completely. And I think there's a really nice place to put this material in the book -- in the data preprocessing section in Classification I. This works well because tidymodels does imputation as a recipe step:

https://recipes.tidymodels.org/reference/index.html

So we can cover it in the same place we cover other recipe steps (standardization, balancing)
