### ISSUE TITLE
Review: Ch 11 (inference) 

### ISSUE THREAD

**Issue by leem44** [UBC-DSCI/introduction-to-datascience#111]
Reviewer E: 
- In overview, give an example of the type of question inference asks and clarify how different than prediction
  - **TC: tentatively agree, but not strongly. will think about it**
- I really like the simulation-based approach to inference used here!
- There is another confusing location of an R-generated plot here. Use more proscriptive “In Figure X” to clarify instead of “below”
  - **TC: need to fix this, i see at least one instance of it** update: fixed
- Although not using analytical approach, it might be worth formally mentioning foundational concepts like the central limit theorem and law of large numbers since students are likely to encounter these in any future study of inference
  - TC: nope, too technical
- Great diagrams throughout the chapter to explain key concepts!
- It’s possibly worth mentioning that in some cases closed form solutions do exist even if you don’t wish to discuss. For example, closed form solutions for something like a binomial probability estimation are so straightforward and well-understood, it might be wasteful to bootstrap to figure this out (outside of a learning context)
  - TC: way too technical

**Comment by leem44** [comment]
Reviewer B: 
- It’s a hard task to cover statistical inference in such constraints (single chapter). However, the large number of histograms and schematics like in Figure 11.11 do make the most of the pages/ink allotted to the topic.

**Comment by trevorcampbell** [comment]
# Reviewer D
- Given the predictive focus of previous chapters, the chapter on statistical inference seems out of place.  It seems to me that it can be removed from the book without sacrificing the quality of the book – this will help with controlling the book length as well. 
- The authors could submit a separate book proposal which focuses on statistical explanation and inference – that would be a valuable follow-up to the current book.
- If the authors feel strongly about retaining this chapter in the current manuscript, I would be happy to provide more detailed feedback on strengthening this chapter upon request.

**Comment by trevorcampbell** [comment]
# Reviewer A
- p241 ("sample point estimate") Are you avoiding the word statistic?
- p241 ("define bootstrapping") Is this bootstrap resampling, bootstrap interval estimation, bootstrap inference? Be more specific for clarity,
- p244 code block: This code snippet made me think that virtual_box was available once the packages were loaded. Be careful here.
- p249 (re tibble block): I'd like to see the # of rows here, so maybe print the tibble rather than the head, this should still suppress most of the rows, but tell us how many more there are.
- p250 \begin{figure} raw latex here
- p254 Make each facet taller for easier reading.
- p255 (re the red line in each figure) Mention the line in the text instead of forcing reader to figure out it's the mean. It's obvious to us, but not to the novice, and it's best to reduce the cognitive load on the reader.
- p259 more raw latex
- p264 vertically aligning these figures would make the comparison between the means clearer
- p264 "We will build..." Consider rewording, maybe start with covering the central 95% and then say that it's a percentile bootstrap CI.
- p266 (code block at top) Why not pull(mean)?
- p266 Maybe add a bit more of a summary of your example before the "this chapter..." paragraph.
- p267 last remark: Maybe point to the types of problems that would require this? Or jobs? The reader gets more of an idea about learning, and just a brief teaser into inference, so they may not see the "so what?"
-

**Comment by trevorcampbell** [comment]
- second last paragraph, both sentences start with "However,"

**Comment by leem44** [comment]
Figure 10.7, 10.14, 10.16 the y-axis says "y" but we should switch it to count

**Comment by trevorcampbell** [comment]
> Figure 10.7, 10.14, 10.16 the y-axis says "y" but we should switch it to count

@leem44 I will open a new issue for those and close this big one (#219 resolved this)
