### ISSUE TITLE
Revise chapter 1 (introduction)

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#114]
Expand the brief introduction paragraph in chapter 1 to be more clear about what the book covers. Specifically:
- ~~tell people how to read the book (might want to read the system setup ~~and version control chapters first~~)~~ (done)
- ~~add data science workflow diagram to beginning of chapter 1, & expand text to make it clearer what is going on~~ (done)
- ~~move `select` & `filter` to wrangling (chapter 3) and make sure this doesn't negatively affect chapter 2~~
- move Jupyter content to System setup/Setting up your computer chapter
    
   This addresses comments by Rev D, Rev A & C. Need to rebut D's ask for a whole new chapter here.

**MAJOR**

**Comment by leem44** [comment]
@ttimbers @trevorcampbell 
One part of this issue is moving `select` and `filter` to ch 3. In chapter 2 we use `select` and `filter` and I think it's pretty important to ch 2 contents (e.g. filtering data so we aren’t collecting on the full data set). I think our options are: 
- keep `select` and `filter` in chapter 1
- move `select` and `filter` to the beginning of ch 2 (but I think this negatively affects the narrative in ch 2) 
- move `select` and `filter` to chapter 3 and briefly explain these functions right before we use them in ch 2 

I vote we keep it in chapter 1, but if either of you feels strongly or has other suggestions let me know!

**Comment by trevorcampbell** [comment]
unrelated to above comment, but:

"Assigning a value to a dataframe" 

is an unclear subsection heading. Should be more like "giving a variable a name" or "giving a dataframe a name" or something like that

**Comment by leem44** [comment]
Thanks! I will make that change to the heading!

**Comment by trevorcampbell** [comment]
@leem44 re: your above comment

After reading through everything, I think I have a decent solution:
- keep `select` and `filter` in chapter 1 (since as you say both get used in 2 -- it's not possible to discuss dbplyr properly without those --- and would break the flow there) 
- but only introduce their simplest use cases -- right now 1.5 contains advanced usage of those two functions, which isn't important for either chapter 1 or 2. Move the advanced usage of them to chapter 3.
- Similarly, 1.6 is way too complicated. `mutate` should be introduced in chapter 3 probably alongside other wrangling functions. 
- Try to simplify the visualization in 1.6 a bit, because it's a bit much for chapter 1. 
    - the `category` aesthetic should be moved to chapter 4
    - the log scaling is another thing that is probably too complicated. Move that stuff to chapter 4. It might be worth thinking of a slightly different visualization (e.g. a bar plot for french + canadian + other or something like that) to avoid having to do log-scaling.
    - in fact, you can use the example currently in chapter 1 as a perfect case where log scaling is required in chapter 4

**Comment by trevorcampbell** [comment]
(what I propose would change things a decent amount, so might want to get a thumbs up from @ttimbers first)

**Comment by leem44** [comment]
Thanks, @trevorcampbell! Yeah, I like those ideas! I was also thinking that the log scale was too complicated for chapter 1 so +1 that comment as well.  I could take the barplot from 3.4.5 and move it to this chapter since we need to filter to create it. 
I will wait to hear from Tiffany before I make any changes!

**Comment by trevorcampbell** [comment]
I would try to go even simpler than that barplot in 3.4.5 for chapter 1 (and also if you pull that barplot out of 3, you may need to replace it with something else. Sounds like more work to me)

**Comment by ttimbers** [comment]
Without changing the narrative of this chapter too much, how about we do the following: we could change the question to how many aboriginal languages are spoken as mother tongues in Canada and how many people speak each of them?

This could be answered with a simple, but informative horizontal bar chart (or these values could even be represented as shapes! And the only data wrangling we need are to filter the rows for Aboriginal languages? 

I do support keeping examples of `select` and `filter` here, but making them simpler. And dropping mutate since we don't need it any longer.

**Comment by ttimbers** [comment]
Let's move the current scatterplot example to chapter 4 as described here in #142

**Comment by leem44** [comment]
addressed all here: #143
