### ISSUE TITLE
Simplify and better explain data sets

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#116]
Where we can, provide more information/context about the data sets (maybe in a call out box or something?). Also, make it clear where things have been simplified and why (so we can focus on the data science method we are teaching). At a minimum, we need to explicitly state that data science **cannot** be done without a deep understanding of data and domain, and that we are approaching things the way we are to teach data science, and IRL data science should not be done without a domain expert, or alternatively, it is common to practice data science in your domain of expertise.*  Go through each chapter and find where we can just have one data set. Idea: see if we can have chapter 2 only use `canlang` data sets (might not work for web scraping, but maybe there's a more related data set? Note: Chapter 4 needs multiple data sets by the way we have written it. Question: Think about clustering chapter - can we use one that we are already using? This addresses comments made by Rev C & E, but we do need to also generate a rebuttal here stating why we have chosen a rich set of data sets for this book. **MAJOR**

**Comment by trevorcampbell** [comment]
One thought from me here: I really like the current way that chapters 6+7 use the breast cancer data, and chapters 8+9 use the sacramento housing data. It doesn't seem like "dataset overload" since each dataset is used over two chapters that focus on one global topic. I forget exactly where our discussions about this issue landed, but count me as a "don't change the datasets we use in ch 6-9". Of course all of the above comments re: making sure to explain and think about the data more deeply still apply.

**Comment by leem44** [comment]
I agree that we shouldn't change the breast cancer or Sacramento data set, and most of the early chapters use the Canadian language data set so I won't touch those. What about the clustering and inference chapters? I remember there were some discussions around changing the clustering one to something else. @trevorcampbell @ttimbers thoughts on these chapters?

**Comment by trevorcampbell** [comment]
@leem44 I think the Palmer penguins data (with the species label removed) for bill depth vs bill length would be a nice example of using clustering to discover subgroups in data. You could even add the labels back in at the very end to show that the clustering procedure found meaningful subgroups (although you'd have to be very careful to mention that if we had labels in the first place, we wouldn't need to cluster).

**Comment by trevorcampbell** [comment]
The inference chapter is definitely an example of "dataset overload" -- there are at least 3 in this chapter alone. I would say pick the AirBnB data (since it's real) and use it for all the examples in that chapter. Try to use it for both the categorical and numerical examples. You could use the `room_type` category with the question like "the govt wants to know how many of the properties are just being rented out vs how many actually have people living and they're sharing their space". The current mean price example is probably fine for the numerical eg.

**Comment by leem44** [comment]
addressed in #144, #149 and #143
