### ISSUE TITLE
Make it clear web scraping is optional/add API's

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#132]
Add a note to make it clear that web scraping is optional. Fix the wrong definition of web scraping. Add a subsection on web API's (we could use this one: https://cran.r-project.org/web/packages/cancensus/vignettes/cancensus.html). **MINOR**

**Comment by ttimbers** [comment]
Another option is https://github.com/ropensci/rtweet

**Comment by ttimbers** [comment]
Trevor thinks we should write our own...

**Comment by trevorcampbell** [comment]
created the `webscraping_optional_and_api` branch for this

**Comment by trevorcampbell** [comment]
@ttimbers @leem44  I'm going to go with the Twitter API. I prefer this one because it's likely to be a lot more stable than others, since lots of things use information from Twitter. I'll make it explicit in the text that this API is nice because it doesn't need any special token biz, and that every API is different so this is just one example.

**Comment by trevorcampbell** [comment]
#138 was merged, closing this issue.
