### ISSUE TITLE
Chapter 4: add nice scatter plot and need for axis scaling example

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#142]
Move the scatter plot example pictured below from chapter 1 as an example in chapter 4 of scatter plots and need for axis scaling. We will need to tighten up the current narrative and but aim to keep the iterative "build up" of the figure.

<img width="905" alt="Screen Shot 2021-05-07 at 12 33 42 PM" src="https://user-images.githubusercontent.com/6865016/117499733-7ae43800-af30-11eb-8b91-88b5a92c2dc6.png">

**Comment by trevorcampbell** [comment]
a few adjustments too:

- the final viz should separate english and french with different colours
- we need to check over all the claims that we make to make sure they're true. For example, right after Fig 1.6, we say "From the visualization above, we can now clearly see that not just a lot, but that the majority of Canadians **reported English as their mother tongue**" but this isn't clear from the figure since none of the languages are coloured yet
