### ISSUE TITLE
Intro of data frame conflated with tidy

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#259]
From a PR review by @leem44 :

In chapter 3:

> since we define very specifically that tidy data is rows = observation and columns = variables etc, should we modify this definition slightly here? e.g. if we had messy data with observations across multiple rows then would we not consider it a data frame in R?

Basically we introduce the concepts needed for *tidy* data right before we introduce general *data frames*. It seems we should move variable/observation/value to where we intro tidy data, and fix the general intro to data frames too.

**Comment by ttimbers** [comment]
OK, I kind of see the issue here.

Data frames are an object in R. They can be tidy, they can be messy. They are a special kind of list that has elements, which must be vectors or lists of the same length.

Tidy data can be a data frame, it could be spreadsheet, it could be a matrix, or it could be a table in a data base.

So why introduce the statistical terms when talking about data frames?

I think it makes sense when we introduce data frames that it is not just done from a CS object perspective. Yes, it is that, but they were designed to hold data for statistics, and to hold things like variables, observations and values.

So how about we soften the language to this: 

```
To help prepare us to do that, 
we need to introduce a few commonly used terms in statistics:

  - **observation** - all of the quantities and/or qualities we collect from a
    given entity/object. An example of an entity/object is a particular person.
  - **variable** - any characteristic, number, or quantity that can be measured
    or collected (*e.g.,* adult height)
  - **value** - a single collected quantity or a quality from a given
    entity/object (*e.g.,* the adult height of a particular person)

From a data perspective, a data frame is a rectangle that was designed to store observations, variables and their values. Commonly the rows are the observations and the columns are the variables:
```

So it's really the last sentence I think we need to change: _"From a data perspective, a data frame is a rectangle that was designed to store observations, variables and their values. Commonly the rows are the observations and the columns are the variables:"_

This setup really helps explain tidy data later, as they have heard these terms and have been primed to map rows to observations and variables to columns. Then we just refine that in the tidy data section.

**Comment by trevorcampbell** [comment]
#261 closed this
