### ISSUE TITLE
specific r package versions in setup chapter

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience#408]
We should edit the install instructions in the setup chapter to include the specific set of package versions that we know work together to run our worksheets.

**Comment by ttimbers** [comment]
I have been thinking about this - I anticipate we will update the worksheets over time... And so in the print version of the book will quickly become outdated if we do this? What about no versions in the textbook - but some documentation about versions in the worksheet repo? Which we at least have written down in the Dockerfile there: 

```
RUN conda install --quiet --yes -c conda-forge \
  r-cowplot=1.1.* \
  r-ggally=2.1.* \
  r-gridextra=2.3 \
  r-infer=0.5.* \
  r-kknn=1.3.* \
  r-rpostgres=1.3.*
```

We could make this more prominent in the README in the worksheets repo?

**Comment by ttimbers** [comment]
(sorry, didn't mean to close this and I am working on a PR to add the versions despite my comments above)

**Comment by trevorcampbell** [comment]
I really like your idea of removing versions from the book to avoid stale material.

*Idea 1*:
- remove all particular package versions from the setup chapter
- tell the reader *how* to specify particular package versions (e.g. the commands that we give them should be like `r-rpostgres=[version_code]`)
- point the reader to the worksheets repo, where we will always put compatible versions of all packages in the readme with each tagged release
- make sure the above "template commands" fail if someone just copy and pastes
- in the book make it super, painfully obvious that they can't just copy and paste, they have to visit the worksheet repo for versions

*Idea 2*:
- remove the R package installation steps entirely from the book
- just say "visit the worksheets repo (at url blah) and follow instructions there to install R package"
- then only in the worksheets repo we give them R package installation instructions
- we make sure each tagged release includes edits to the readme files to ensure that all worksheets run smoothly

I kind of prefer idea 2 above -- simpler, less confusing instructions for readers.

**Comment by ttimbers** [comment]
More thoughts on this - it takes 2 min to install the packages if we do not pin versions. If we pin versions, it takes FOREVER (actually I can't even get it to work on an ubuntu image yet, still working on it)...

I think the setup chapter plays a role greater than just running the exercises - it will help folks get setup so they can run some of the code in the book, and start doing their own analysis. In these situations it is less critical that they have the exact versions we use for the worksheets. 

Also, for the worksheets, since we have the Binder links (and I will add instructions so they can run Docker locally too) I think most people will use that for the exercises, and not run things locally... 

But if you feel strongly, I can make it work (it FINALLY just finished solving), but we need to pin all the way to the patch version - this works:

```
conda install -c conda-forge -y \
  r-cowplot=1.1.1 \
  r-ggally=2.1.2 \
  r-gridextra=2.3 \
  r-kknn=1.3.1 \
  r-rpostgres=1.3.3 \
  r-rsqlite=2.2.5 \
  r-scales=1.1.1 \
  r-testthat=3.0.4 \
  r-tidymodels=0.1.3 \
  r-tidyverse=1.3.1 \
  r-tinytex=0.33 \
  unixodbc=2.3.9
```

**Comment by ttimbers** [comment]
OK, plan is to:

1. remove pinned package versions from the textbook
2. tell them that if they want the package versions that the worksheets were designed with they should install from our [`environment.yml` file](https://github.com/UBC-DSCI/data-science-a-first-intro-worksheets/blob/main/environment.yml) (and give them the command on how to do so). (We also use this file to create the environments for the worksheet with Binder)
