### ISSUE TITLE
Figure 8.10: plot axis titles and figure captions do not match narrative text

### ISSUE THREAD

**Issue by GloriaWYY** [UBC-DSCI/introduction-to-datascience#443]
In [Section 8.7.2 Multicollinearity](https://datasciencebook.ca/regression2.html#multicollinearity), Figure 8.10 has x axis title “House size (square feet)” and y axis title “House size (square inches)”. However, these do not match the actual plot (where the x values and y values are very close) and the narrative text:
> Consider an extreme example using the Sacramento housing data where the house was measured twice by two people. Since the two people are each slightly inaccurate, the two measurements might not agree exactly, but they are very strongly linearly related to each other, as shown in Figure [8.10](https://datasciencebook.ca/regression2.html#fig:08-lm-multicol).

**Comment by trevorcampbell** [comment]
This is already fixed in the `dev` branch!

@GloriaWYY I guess I forgot that this might come up: when you're looking at the R version of the book, you should look on the `dev` branch -- it's got some updates that the `master` branch doesn't have yet.

(we can't update `master` now because the course is currently being taught -- we'll be merging `dev -> master` soon though.)
