### ISSUE TITLE
Review: Global/big picture formatting revisions

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience#96]

**Comment by leem44** [comment]
From reviewer E: 
- placement of figures is confusing throughout this text (e.g. Sections 1.62, 4.5.2). figures are often far from what they described; sometimes even directly under the wrong code chunk. 
  - recommend forcing appropriate figure placement or, at minimum, using more specific language of “In Figure X, we see…” instead of “in the plot below”.
- code frequently spills out over the textboxes. may need to split some commands across more lines or change the font.

**Comment by trevorcampbell** [comment]
# Reviewer D
- background colour used for the figures is not always consistent.  Some figures use the default grey theme of ggplot, while others don’t.  The grey theme is not the best default so perhaps the authors could consider using a more visually appealing theme.  
- There aren’t many tables in the manuscript and I think this is a missed opportunity. I could only find one table, which lists the questions typical of various kinds of statistical analyses but even this was borrowed from a different source and included in the manuscript without much of a preamble.  Tables are a great way to show information side-by-side (e.g., pros and cons of a statistical procedure) or to list various options the students can consider (e.g., different types of geoms that could be used to build a ggplot; different types of R import functions that could be used to read in different types of data files). It would be good if the authors could add a few more tables to the manuscript. 
    - This is not a bad idea, especially for chapters with a lot of such "options" (viz is a great example)
    - Just to be clear: tables should not be used for conveying numerical/statistical results/comparisons. Figures are always better.

**Comment by trevorcampbell** [comment]
# Reviewer A
- the color schemes should be carefully chosen so that colorblind readers have no problem reading them. Double encoding could also be used to help with this.
- From a typesetting perspective, there are some problems with the figures in the PDF (but not the HTML version). In the PDF, the figures often fall too far from the discussion or code snippet. There is certainly some tweaking to be done in typesetting, but I also think that it is important to explicitly point to the figure being discussed for the print edition. 
- the book is of the right length for an introduction
- be sure no code gets cut off and that figures are placed as close to the text as possible.

**Comment by trevorcampbell** [comment]
# Trevor
- we say "Professor Claus Wilke" and "Grolemund & Wickham" when referring to textbooks. We should go through and make sure we reference other resources in a consistent way

**Comment by trevorcampbell** [comment]
### Edit this comment directly to summarize / synthesize the major (important) comments across reviewers. If there's already the same comment below, add the reviewer to the parenthetical list at the beginning.

# Synthesis:
- Figure placement overall is confusing and broken. We need to add reference anchors to all figures, and then make sure to reference those anchors in the text.
- plot background colours should be consistent (some are ggplot grey, some are not)
- Code blocks often spill over the edge, math is formatted poorly.
- some reviewers thought it was too long (D), some thought just right (A). I think it's fine.
- consistency of spelling (color vs colour, data set vs dataset, scatter plot vs scatterplot)
- clearer / nicer typography of "Note:" blocks including a block title of some sort
- choose colourblind friendly colourschemes for all chapters (e.g. Ch10 is particularly bad)

**Comment by ttimbers** [comment]
# Reviewer F
- The book is black/white but refers to colour highlighting in JP

**Comment by ttimbers** [comment]
# Reviewer C
- This is a minor point, but there are places where parts of the code are grayed out – I presume this is a result
of converting colorized code to black and white. Given that some of the plots are in color, I presume the
book will be printed full-color, in which case the color could be retained for the code. If that isn’t to be
done, please convert all code to simple black and white.

**Comment by leem44** [comment]
Adding from

**Comment by leem44** [comment]
How should we display links to video content, such as this line from Ch 13: "Thus, we recommend you change the default shell to Bash by opening the terminal (how-to video) and typing:"

**Comment by trevorcampbell** [comment]
In the Jupyter chapter (where there were other videos) we just replaced them with static screenshot images. I would be fine with that strategy throughout. I would also be fine with linking to some other static online resource for little things like "open a terminal" (so you could e.g. just put a link to Tiffany's youtube video).

@ttimbers what do you think?

**Comment by ttimbers** [comment]
"Figure 4.16 on page 102 does not highlight the artifacts the same way the web version does... did we accidentally load the same image twice?"

**Comment by ttimbers** [comment]
A couple of things that I didn't comment on but we should add to the formatting pass:

sometimes the caption has periods at the end, sometimes it doesn't -- we should add this to the style guide which one we want
the plots and code coming off the page + the placement of figures -- add to formatting pass

**Comment by trevorcampbell** [comment]
All of these things are either handled, already in the style guide, or in open issues (which may add them to style guide).
